### ISSUE TITLE
调用服务问题

### ISSUE THREAD

**Issue by LCRONG** [hprose/hprose-yii#11]
$user = new Client('http://localhost/core/user');
$uid = $user->create([
    'name' => 'Hprose',
]);
这个create方法中的参数不是需要传入一个索引数组吗，为什么在hprose for yii  wiki中的使用方式是传入关联数组呢?

**Comment by pavlelee** [comment]
你能详细描述一下吗？没看懂你说的

**Comment by LCRONG** [comment]
在[这个链接中](https://github.com/hprose/hprose-yii/wiki/%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)的调用服务的代码,是不是少了useService()这个方法的调用

**Comment by andot** [comment]
1、useService 不是必须的。new Client 的时候填写了服务地址，就不需要使用 useService 再设置一次地址了。

2、create 方法的参数是需要跟：

```php
class UserService {
    /**
     * 创建用户
     * @param array $data
     * @return int
     */
    public function create($data) {
        //你的逻辑
    }
}
```

这个服务中定义的 create 方法的参数格式一致的，这个例子中并没有给出create方法的业务逻辑实现，所以单从这个create方法的签名中，看不出它是一个索引数组还是关联数组。后面调用这个例子时，参数是关联数组，只是假设这个create方法在实现业务逻辑时，参数就是关联数组。
