### ISSUE TITLE
求助！！！

### ISSUE THREAD

**Issue by linxu** [hprose/hprose-yii#4]
可否提供yii版的example？？？

**Comment by andot** [comment]
用法跟 http 的 server 一样。只是创建的类是 Hprose\Yii\Server，其它操作一模一样。

**Comment by linxu** [comment]
class ServerController extends Controller
{
    public function actionIndex()
    {
        $server = new Server();
        $server->addInstanceMethods($this);
        $server->start();
    }
    public function hello($name) {
        return 'hello'.$name;
    }
}

class ClientController extends Controller
{
    public function actionIndex()
    {
        $client = new Client('http://test.com/server', false);
        return $client->hello('123');
    }
}

这样写对嘛？可是调用不成功，报400

**Comment by linxu** [comment]
php的方式没问题 用yii的方式就报错 求大神指点或者给个yii的例子

**Comment by andot** [comment]
服务方法不应该写在控制器中，这种写法是不好的。你可以直接发布一个模型什么的。控制器只是一个入口。

**Comment by linxu** [comment]
能否提供点例子，不是很明白~

**Comment by linxu** [comment]
<?php
require_once "../../vendor/autoload.php";
use Hprose\Http\Server;
function hello($name) {
    return "Hello $name!";
}
$server = new Server();
$server->addFunction('hello');
$server->start();

如果用php的方式这样写，那yii要怎么使用？

**Comment by linxu** [comment]
小白还是不懂，能否提供个完整的例子？

**Comment by pavlelee** [comment]
@linxu https://github.com/hprose/hprose-yii/wiki/%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95

**Comment by linxu** [comment]
@Liv1020 按照你的方法写了 服务端可以正常放回Fa2{u#s5"hello"}z数据 之前也是可以的 可是client调用服务还是报400错误

**Comment by linxu** [comment]
你们可以排查下，我觉得是yii调用这块有bug！

**Comment by Liv1020** [comment]
不可能，我们项目面对千万用户已经在使用，也是yii的解决方案

**Comment by pavlelee** [comment]
@linxu 不可能，我们项目面对千万用户已经在使用，也是yii的解决方案。请粘贴400请求的错误信息

**Comment by linxu** [comment]
![image](https://cloud.githubusercontent.com/assets/1835511/19585217/2c6c4098-977d-11e6-9977-93f3b1f1962a.png)
![image](https://cloud.githubusercontent.com/assets/1835511/19585244/68a4eee8-977d-11e6-953b-fbf1cae8788d.png)

**Comment by linxu** [comment]
class ServerController extends Controller
{
    public function actionIndex()
    {
        $helloService = new HelloService();
        $server = new Server();
        $server->addInstanceMethods($helloService);
        return $server->start();
    }
}

class ClientController extends Controller
{
    public function actionIndex()
    {
        $client = new Client('http://test.com/server', false);
        return $client->hello('123');
    }
}

**Comment by pavlelee** [comment]
@linxu 你是在虚拟机里面开发的吗？

**Comment by linxu** [comment]
不是啊 正常的环境 win7 xampp

**Comment by linxu** [comment]
知道怎么解决嘛？或者有什么方式可以找出问题所在？

**Comment by linxu** [comment]
@Liv1020 找到原因了 原来是yii enableCsrfValidation导致的

**Comment by andot** [comment]
谢谢反馈，我会把这个问题写到帮助的。
