### ISSUE TITLE
请求默认是异步执行，如何改为同步执行？

### ISSUE THREAD

**Issue by linxu** [hprose/hprose-yii#5]
请求默认是异步执行，如何改为同步执行？

**Comment by andot** [comment]
创建一个同步的 HTTP 客户端

```
$client = new \Hprose\Http\Client('http://hprose.com/example/', false);
```

**Comment by linxu** [comment]
好的 谢谢~

**Comment by Lao-liu** [comment]
@linxu 在 new Client() 的时候，第一个参数是接口地址，第二个参数就是同步还是异步。

同步调用：
`$client = new \Hprose\Http\Client('http://hprose.com/example/', false);`

默认是异步：

`$client = new \Hprose\Http\Client('http://hprose.com/example/');`
