### ISSUE TITLE
hprose接口是否存在缓存机制？

### ISSUE THREAD

**Issue by linxu** [hprose/hprose-yii#6]
请求远程接口数据有缓存怎么解决？一段时间后才能获取最新数据！

**Comment by andot** [comment]
文档里有说明：

* [缓存调用](https://github.com/hprose/hprose-php/wiki/12.-Hprose-%E4%B8%AD%E9%97%B4%E4%BB%B6#%E7%BC%93%E5%AD%98%E8%B0%83%E7%94%A8)
* [压缩、缓存、计时](https://github.com/hprose/hprose-php/wiki/12.-Hprose-%E4%B8%AD%E9%97%B4%E4%BB%B6#%E5%8E%8B%E7%BC%A9%E7%BC%93%E5%AD%98%E8%AE%A1%E6%97%B6)

**Comment by linxu** [comment]
默认应该不存在缓存的问题吧？

**Comment by andot** [comment]
嗯，默认无缓存。

**Comment by linxu** [comment]
好的 多谢~

**Comment by andot** [comment]
不客气
