### ISSUE TITLE
hprose权限验证

### ISSUE THREAD

**Issue by linxu** [hprose/hprose-yii#8]
假如身份验证不通过 中间件要怎么返回结果？

**Comment by andot** [comment]
你想返回什么，就返回什么。

**Comment by linxu** [comment]
不是很明白要怎么放回结果，求大神解答！

**Comment by linxu** [comment]
public function synchandle($name, array &$args, stdClass $context, Closure $next) {
        if(!$pass) {
            return Json::encode([
               'status' => false,
                'msg' => '无权限访问'
            ]);
        }
        $response = $next($name, $args, $context);
        return $response;
    }

**Comment by linxu** [comment]
返回json对象不可以吧？

**Comment by pavlelee** [comment]
我建议抛出异常，这样client可以通过异常方式处理

**Comment by linxu** [comment]
好的 我试试
