### ISSUE TITLE
http 同步调用方式出现报错 用异步方式无返回数据 是什么原因啊？

### ISSUE THREAD

**Issue by tairuichen** [hprose/hprose-yii#9]
同步调用报错：
An Error occurred while handling another error:
exception 'ReflectionException' with message 'Method Hprose\HandlerManager::Hprose\{closure}() does not exist' 

异步调用数据返回：
object(Hprose\Future)#38 (4) { ["state":"Hprose\Future":private]=> int(0) ["value":"Hprose\Future":private]=> NULL ["reason":"Hprose\Future":private]=> NULL ["subscribers":"Hprose\Future":private]=> array(0) { } }

用的是官方文档里的代码稍微改了下
client.php

```
$user = \Hprose\Client::create ( 'http://localhost/hprose-server/user' );
$result = $user->hello ();
var_dump($result) ;
exit;
```

server.php
```
public function actionUser() {
		$service = new HproseUser ();
		
		$server = new Server ();
		$server->addInstanceMethods($service);
		
		return $server->start ();
	}
```

**Comment by andot** [comment]
你创建了一个异步客户端，却用了同步调用。

**Comment by pavlelee** [comment]
我测试了同步、异步调用，都是没有问题的。您能提供客户端、服务端、服务的代码吗？
